In [2]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import squareform, pdist

In [3]:
df = pd.read_excel("C:/Users/v-yaagarwal/Downloads/KMeans_Data/Test Data.xlsx")

In [4]:
df.head()

,S.No,,Domain,Workspace,Report Name,Table Name,KPI/Used Columns,Type,Expression,Repeated,Consolidate (Yes/No),Consolidated Report Name
0,1,PBI,NaN,2.\tService,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,PBI,NaN,2.\tService,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,PBI,NaN,2.\tService,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,PBI,NaN,2.\tService,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PBI,NaN,2.\tService,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.describe()

                S.No  Repeated  Consolidate (Yes/No)  Consolidated Report Name
count  145931.000000       0.0                   0.0                       0.0
mean    72966.000000       NaN                   NaN                       NaN
std     42126.795404       NaN                   NaN                       NaN
min         1.000000       NaN                   NaN                       NaN
25%     36483.500000       NaN                   NaN                       NaN
50%     72966.000000       NaN                   NaN                       NaN
75%    109448.500000       NaN                   NaN                       NaN
max    145931.000000       NaN                   NaN                       NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145931 entries, 0 to 145930
Data columns (total 12 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   S.No                      145931 non-null  int64
 1                             145931 non-null  object
 2   Domain                    145729 non-null  object
 3   Workspace                 145931 non-null  object
 4   Report Name               144164 non-null  object
 5   Table Name                22056 non-null   object
 6   KPI/Used Columns          142975 non-null  object
 7   Type                      142976 non-null  object
 8   Expression                34464 non-null   object
 9   Repeated                  0 non-null       float64
 10  Consolidate (Yes/No)      0 non-null       float64
 11  Consolidated Report Name  0 non-null       float64
dtypes: float64(3), int64(1), object(8)
memory usage: 13.4+ MB

In [7]:
df['Report Name'].nunique()

2535

In [8]:
df['KPI/Used Columns'].nunique()

22936

In [9]:
dff = df[["Report Name","KPI/Used Columns"]].dropna().reset_index()

In [10]:
dff.drop(["index"],axis=1,inplace=True)

In [11]:
dff.head()

                        Report Name        KPI/Used Columns
0  01 Dayforce Call Driver Analysis  % Clients with Tickets
1  01 Dayforce Call Driver Analysis            % Enterprise
2  01 Dayforce Call Driver Analysis                % Global
3  01 Dayforce Call Driver Analysis                 % Major
4  01 Dayforce Call Driver Analysis               % Managed

In [12]:
print(dff['Report Name'].nunique())
print(dff['KPI/Used Columns'].nunique())

526
22591

In [13]:
dff["KPI/Used Columns"]

0          % Clients with Tickets
1                    % Enterprise
2                        % Global
3                         % Major
4                       % Managed
                   ...
141595                    Website
141596                 WFM_Vendor
141597            ACV Based on EW
141598          Remaining To Meet
141599    Remaining To Meet Floor
Name: KPI/Used Columns, Length: 141600, dtype: object

In [14]:
matrix = pd.get_dummies(dff['KPI/Used Columns'])

In [15]:
matrix.head()

,"""Subject""",#,# Accounts,# Applicants,# Cal. Columns,# Columns,# Completion Date Issues,# Cust Req KO Issues,# DF Datasources,# DataFlows,...,zSumMaxClientsYear,zref1,zzz,|,| A >,| NA >,|_1,|_2,|_3,|_4
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
dff = pd.concat([dff, matrix], axis=1)

In [17]:
grp = dff.groupby('Report Name').sum()

C:\Users\v-yaagarwal\AppData\Local\Temp\ipykernel_22476\3726598385.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grp = dff.groupby('Report Name').sum()

In [18]:
dist = pdist(grp, metric="jaccard")
s_dist = squareform(dist)
# Fill diagonals with nulls
np.fill_diagonal(s_dist, np.nan)

In [19]:
sim = np.subtract(1, s_dist)

In [20]:
sim_df = pd.DataFrame(sim, columns=grp.index, index=grp.index)

In [21]:
sim_df.head()

Report Name,01 Dayforce Call Driver Analysis,02 Call Drivers by Module,03 Call Drivers by Module First Year Clients,04 Call Drivers by Client Group,05 Call Drivers by Specialty Team,05.19_Services Analytics,05.19_Services Analytics_Historical UTil,06 Client Tenure Ticket Metrics,07 Support Team Metrics,08 Appendix,...,ace,call driver text analysis,handraised Customer MQLs with attributed pipeline,iLinx Queues,mismatch Master/subs,payrollFocusSegment,pipelineTrends,sla_overview_V1,test custom visual,test_pbi_gateway_connectivity
Report Name,,,,,,,,,,,,,,,,,,,,,
01 Dayforce Call Driver Analysis,NaN,0.551020,0.551020,0.581633,0.540000,0.004231,0.004231,0.131313,0.0,0.330097,...,0.003517,0.026239,0.0,0.009434,0.009434,0.005319,0.0,0.008475,0.017391,0.0
02 Call Drivers by Module,0.551020,NaN,1.000000,0.915254,0.898305,0.002994,0.002994,0.206897,0.0,0.397059,...,0.001230,0.019737,0.0,0.010870,0.010870,0.006849,0.0,0.013158,0.027397,0.0
03 Call Drivers by Module First Year Clients,0.551020,1.000000,NaN,0.915254,0.898305,0.002994,0.002994,0.206897,0.0,0.397059,...,0.001230,0.019737,0.0,0.010870,0.010870,0.006849,0.0,0.013158,0.027397,0.0
04 Call Drivers by Client Group,0.581633,0.915254,0.915254,NaN,0.916667,0.002981,0.002981,0.237288,0.0,0.420290,...,0.001225,0.022876,0.0,0.010753,0.010753,0.006711,0.0,0.012658,0.026316,0.0
05 Call Drivers by Specialty Team,0.540000,0.898305,0.898305,0.916667,NaN,0.002985,0.002985,0.200000,0.0,0.385714,...,0.001227,0.019608,0.0,0.010791,0.010791,0.000000,0.0,0.012821,0.026667,0.0

In [40]:
a=[]
for i,r in sim_df.iterrows():
    for j in r.index:
        if r[j] > 0.85:
            # print('1st Report:',i)
            # print('2nd Report:',j)
            # print('Matching %:',round(r[j]*100,3),'\n')
            a.append([i,j,r[j]])

In [42]:
len(a)

2234

In [56]:
a=[]
print('Report Name','##','No. of matching reports','##','Sum of %','##','Avg Matching %')
for i,r in sim_df.iterrows():
    # print('Report:',i)
    s=0
    x=0
    for j in r.index:
        if r[j]>0.85:
            x+=1
            s+=r[j]
    if x!=0:
        b=[i,x,s,(s*100)/x]
        a.append(b)
        # print(b)

Report Name ## No. of matching reports ## Sum of % ## Avg Matching %

In [59]:
print('Report Name','##','No. of matching reports','##','Sum of %','##','Avg Matching %')
for i in a:
    if i[1]>25:
        print(i)

Report Name ## No. of matching reports ## Sum of % ## Avg Matching %
['2021 02 02 - Arthur Powerpay Test', 30, 30.0, 100.0]
['2021 02 03 - Powerpay Managed Test', 30, 30.0, 100.0]
['CDN SBS Implementation - Test', 30, 30.0, 100.0]
['Core Survey Detail - TEST', 30, 30.0, 100.0]
['Customer Support - Canada Payroll (Bureau)', 30, 30.0, 100.0]
['Customer Support - Canada Payroll (Managed)', 30, 30.0, 100.0]
['Customer Support - Canada Small Business', 30, 30.0, 100.0]
['Customer Support - Customer Support Total', 30, 30.0, 100.0]
['Customer Support - Dayforce', 30, 30.0, 100.0]
['Customer Support - Dayforce Managed Services', 30, 30.0, 100.0]
['Customer Support - Service Canada Test', 30, 30.0, 100.0]
['Customer Support - Service Canada Test - 2', 30, 30.0, 100.0]
['Customer Support - Survey Detail - CORE SMB Tax', 30, 30.0, 100.0]
['Customer Support - Survey Detail - Dayforce', 30, 30.0, 100.0]
['Customer Support - Survey Detail - Service Canada', 30, 30.0, 100.0]
['Customer Support - US  Core SMB & Tax', 30, 30.0, 100.0]
['Implementation - All', 30, 30.0, 100.0]
['Implementation - Dayforce', 30, 30.0, 100.0]
['Implementation - Small Business Powerpay', 30, 30.0, 100.0]
['Implementation - Small Business Powerpay REDONE', 30, 30.0, 100.0]
['Implementation - Survey Detail - Dayforce', 30, 30.0, 100.0]
['Implementation - Survey Detail - Small Market - Micro Managed', 30, 30.0, 100.0]
['Implementation - Survey Detail - Small Market - Micro Powerpay', 30, 30.0, 100.0]
['Implementation - Survey Detail - Small Market - US SMB', 30, 30.0, 100.0]
['NPS - Summary', 30, 30.0, 100.0]
['NPS Shared Dataset', 30, 30.0, 100.0]
['Professional Services', 30, 30.0, 100.0]
['Professional Services - Survey Detail', 30, 30.0, 100.0]
['Survey Detail - Canada - Test', 30, 30.0, 100.0]
['Tax Data', 30, 30.0, 100.0]
['Tax Test - All Data', 30, 30.0, 100.0]